### ISSUE TITLE
LSL muse device with uvicmuse doesn't read 

### ISSUE THREAD

**Issue by andraderenew** [nikolaims/nfb#42]
Dear @nikolaims:
I am not able to connect to nfb with LSL with my muse device. I use the name I always use in other software but it doesn't work. I'm sure the issue is mine but I don't know where to ask about this issue.

**Comment by andraderenew** [comment]
/Users/andraderenew/Downloads/nfb-master/pynfb/brain.py:26: UserWarning: Currently info is read from the raw file. TODO: change to getting it from the stream
  warn('Currently info is read from the raw file. TODO: change to getting it from the stream')
Traceback (most recent call last):
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/settings_widget/__init__.py", line 59, in onClicked
    self.experiment = Experiment(self.app, self.params)
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/experiment.py", line 44, in __init__
    self.restart()
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/experiment.py", line 509, in restart
    self.main = MainWindow(signals=self.signals,
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/windows/__init__.py", line 213, in __init__
    source_space_protocol = SourceSpaceRecontructor(signals)
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/brain.py", line 19, in __init__
    self._forward_model_matrix = self._assemble_forward_model_matrix(inverse_operator)
  File "/Users/andraderenew/Downloads/nfb-master/pynfb/brain.py", line 40, in _assemble_forward_model_matrix
    stc = mne.minimum_norm.apply_inverse_raw(dummy_raw, inverse_operator, lambda2, method)
  File "<decorator-gen-334>", line 24, in apply_inverse_raw
  File "/Users/andraderenew/opt/anaconda3/envs/nfb/lib/python3.9/site-packages/mne/minimum_norm/inverse.py", line 1041, in apply_inverse_raw
    _check_reference(raw, inverse_operator['info']['ch_names'])
  File "/Users/andraderenew/opt/anaconda3/envs/nfb/lib/python3.9/site-packages/mne/minimum_norm/inverse.py", line 793, in _check_reference
    raise ValueError('Custom EEG reference is not allowed for inverse '
ValueError: Custom EEG reference is not allowed for inverse modeling.


I also have this error. I don't know how to solve.

**Comment by andraderenew** [comment]
another issue I see is when I click on protocol I can't do anything because the window is to large and I cannot shrink it. so I have to use ctrl + z.

**Comment by andraderenew** [comment]
I have seen in this youtube video https://www.youtube.com/watch?v=rEkjLjgaFW0 minute 20 forward that they use some feedback I don't know how to execute that is it something with nfb lab or does it depend on the programmer?
